create database if not exists ecommerce;
USE ECOMMERCE;
CREATE TABLE IF NOT EXISTS CATEGORY(
CAT_ID INT,
CAT_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY(CAT_ID));

CREATE TABLE IF NOT EXISTS PRODUCT(
PRO_ID INT,
PRO_NAME VARCHAR(20) NOT NULL DEFAULT 'DUMMY',
PRO_DESC VARCHAR(60),
CAT_ID INT,
PRIMARY KEY(PRO_ID),
foreign key(CAT_ID) references CATEGORY(CAT_ID));

CREATE TABLE IF NOT EXISTS SUPPLIER(
SUPP_ID INT PRIMARY KEY,
SUPP_NAME VARCHAR(50) NOT NULL,
SUPP_CITY VARCHAR(50) NOT NULL,
SUPP_PHONE VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS SUPPLIER_PRICING(
PRICING_ID INT PRIMARY KEY,
PRO_ID INT,
SUPP_ID INT,
SUPP_PRICE INT DEFAULT 0,
foreign key(PRO_ID) references PRODUCT(PRO_ID),
foreign key(SUPP_ID) references SUPPLIER(SUPP_ID));

CREATE TABLE IF NOT EXISTS CUSTOMER(
CUS_ID INT PRIMARY KEY,
CUS_NAME VARCHAR(20) NOT NULL,
CUS_PHONE VARCHAR(10) NOT NULL,
CUS_CITY VARCHAR(30) NOT NULL,
CUS_GENDER CHAR);

CREATE TABLE IF NOT EXISTS ORDERS(
ORD_ID INT PRIMARY KEY,
ORD_AMOUNT INT NOT NULL,
ORD_DATE DATE NOT NULL,
CUS_ID INT,
PRICING_ID INT,
FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
FOREIGN KEY (PRICING_ID) REFERENCES SUPPLIER_PRICING(PRICING_ID));

CREATE TABLE IF NOT EXISTS RATING(
RAT_ID INT PRIMARY KEY,
ORD_ID INT,
RAT_RATSTARS INT NOT NULL,
foreign key(ORD_ID) references ORDERS(ORD_ID));

